# theme by 60hz on the pure data forum
# https://forum.puredata.info/topic/10943/a-little-pd-mod

array set ::pd_colors {
selected "orange"
selection_rectangle "orange"
txt_highlight "grey"
txt_highlight_front "orange"
msg_iolet "grey15"
signal_iolet "grey15"
msg_iolet_border "grey15"
signal_iolet_border "blue"
obj_box_outline "grey35"
obj_box_fill "grey35"
obj_box_text "grey80"
msg_box_outline "grey80"
msg_box_fill "grey80"
msg_box_text "#000"
atom_box_outline "grey35"
atom_box_fill "grey80"
atom_box_text "#000"
atom_box_label "#000"
msg_cord "grey35"
signal_cord "blue"
obj_box_outline_broken "blue"
canvas_fill "grey60"
comment "#000"
graph_outline "grey25"
graph_text "#000"
array_name "#000"
array_values "#000"
gop_box "#FF8080"
text_window_fill "grey25"
text_window_text "#FFFFFF"
text_window_highlight "orange"
text_window_cursor "#FFFFFF"
canvas_text_cursor "orange"
pdwindow_fill "grey25"
pdwindow_fatal_text "#D00"
pdwindow_fatal_highlight "#FFE0E8"
pdwindow_error_text "#D00"
pdwindow_post_text "#FFFFFF"
pdwindow_debug_text "#808080"
helpbrowser_fill "grey25"
helpbrowser_text "#FFFFFF"
helpbrowser_highlight ""
}
