# theme by 60hz on the pure data forum
# https://forum.puredata.info/topic/10943/a-little-pd-mod

array set ::pd_colors {
selected "#FF8022"
selection_rectangle "#FF8022"
txt_highlight "grey15"
txt_highlight_front "#FF8022"
msg_iolet "grey10"
signal_iolet "red"
msg_iolet_border "grey10"
signal_iolet_border "red"
obj_box_outline "grey40"
obj_box_fill "grey40"
obj_box_text "grey85"
msg_box_outline "grey85"
msg_box_fill "grey85"
msg_box_text "#000"
atom_box_outline "grey85"
atom_box_fill "grey85"
atom_box_text "#000"
atom_box_label "#000"
msg_cord "grey10"
signal_cord "red"
obj_box_outline_broken "red"
canvas_fill "grey62"
comment "#000"
graph_outline "grey25"
graph_text "#000"
array_name "#000"
array_values "#000"
gop_box "#FF3232"
text_window_fill "grey25"
text_window_text "#FFFFFF"
text_window_highlight "grey35"
text_window_cursor "#FFFFFF"
pdwindow_fill "grey25"
pdwindow_fatal_text "#D00"
pdwindow_fatal_highlight "#FFE0E8"
pdwindow_error_text "#D00"
pdwindow_post_text "#FFFFFF"
pdwindow_debug_text "#808080"
helpbrowser_fill "grey25"
helpbrowser_text "#FFFFFF"
helpbrowser_highlight "grey45"
}
set ::pd_colors(atom_box_focus_outline) $::pd_colors(atom_box_outline)